### ISSUE TITLE
Frictionless (Data Package) <=> CKAN

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/forum#11]
Quick recipe (maybe evolving into a lib) for mapping from CKAN metadata <=> Frictionless specs

Job story: When getting data in and out of CKAN I'm frequently using Frictionless formats and tools (its my default format for extraction from other systems) and I want to be able to do conversion to and from CKAN metadata structure so that I can do my work quickly and without having to dig through CKAN documentation.

Bigger context: frequently pulling data from other systems into CKAN -- and from CKAN into other systems. We want to use Frictionless as the intermediate format so we can convert MxN into M+N problem.

```
Frictioness   <=>     CKAN
---------------------------
Data Package  <=>   Dataset
Data Resource <=>   Resource
Table Schema  <=>   ?? (datastore resources can have schemas)
```

## Acceptance

* [ ] Documenation 

## Tasks

* [ ] Document CKAN metadata
* [ ] Comparison / mapping of Frictionless <=> CKAN
* [ ] Simple script (python and/or JS) to convert (recipe / howto on f15a.io)

**Comment by roll** [comment]
@rufuspollock 
@lauragift21
FYI there is https://github.com/frictionlessdata/tableschema-ckan-datastore-py#getting-started.

I'm not sure if it can just read from public CKAN without an API key (cc @amercader). But in general, it should be possible to use it like any other `tableschema` driver:

```python
package = Package(
           storage='ckan_datastore', 
           base_url=base_url,
           dataset_id=dataset_id,
           api_key=api_key)
# work with ckan dataset as with data package
```

I can check the sate of the driver if needed. It was written long ago I guess by Brook.

**Comment by rufuspollock** [comment]
@roll great 😄 Can you show/share a minimum viable code snippet of using this code "in action"?

My use case was converting a data package *to* ckan metadata - and then doing some further manipulation b4 storing. So I just wanted the raw convert of the schema from one dict to another - do we have a recipe or function that does just the simple conversion?

**Comment by roll** [comment]
@lauragift21 
@rufuspollock 
I don't think we have something for the low-level conversion of metadata formats. I've played with the Tableschema-CKAN driver - it's quite raw but I was able to use it for exporting data from a CKAN dataset.

Here is a script based on @lwinfree's template for tutorials - https://colab.research.google.com/drive/18xFFAooVcca5wfW-7hW_juLkaTdN9FI0#scrollTo=Qv9bmfRA756R (I used Pandas as a target platform but it can be SQL/etc)

Also, having a CKAN API KEY one should be able to import a data package as a CKAN dataset (not yet testedthough)

PS.
At least it's really aligned with what described here:

> Bigger context: frequently pulling data from other systems into CKAN -- and from CKAN into other systems. We want to use Frictionless as the intermediate format so we can convert MxN into M+N problem.

**Comment by rufuspollock** [comment]
I've added an example simple python script to the description.
