### ISSUE TITLE
[epic] Inventory existing data profile and schema formats and compare / map against Frictionless

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/forum#53]
Done this informally many times over the years. Let's do it systematically and once and for all.

Inventory in progress here: https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=774748003

## Job Stories

When developing or using Frictionless tools for interfacing with format X i want to know how the metadata / schema map so that I can I quickly and reliably do my work

When considering using Frictionless and already familiar with X format I want to know how they compare and how i can map so that I can decide whether to use and how to use

## Acceptance

* [ ] A listing of existing profile and schema formats
* [ ] Key dimensions and attributes for classifying these
* [ ] Mapping of these against Frictionless
* [ ] Write up website somewhere

## Tasks

* [ ] NetCDF #51 
* [ ] Protocol buffer (protobuf) #48 
* [ ] CKAN #11 
* [ ] ...

**Comment by dafeder** [comment]
Other suggestions:

- DCAT-AP
- Schema.org as used by Google Dataset Search
- ISO 19115

**Comment by dafeder** [comment]
I'm wondering if there's an existing format for expressing this kind of mapping, which could be technology-independent. For instance if there's a standardized way to explain a one-way (or maybe even a two-way) mapping, we can support an ecosystem of translation tools (Python, JS, PHP, Safe FME plugin, etc) that share a common mapping collection.

**Comment by rufuspollock** [comment]
> I'm wondering if there's an existing format for expressing this kind of mapping, which could be technology-independent. For instance if there's a standardized way to explain a one-way (or maybe even a two-way) mapping, we can support an ecosystem of translation tools (Python, JS, PHP, Safe FME plugin, etc) that share a common mapping collection.

@dafeder i wondered this too 😄 and would love to hear of one. Essentially it's just a graph (nodes with edges) - perhaps with detail on the edges which is very standard and you can represent in lots of ways. I just don't know of a *nice* editor for that kind of stuff hence the use of the spreadsheet. From the spreadsheet you can produce other formats and if there were some format with nice visualization that would be really cool.
